// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEuih9Hl7DpEwrtbwfng03q4Bo20F3fo',
    appId: '1:769803144200:ios:05f2eb9a9c600637df15bd',
    messagingSenderId: '769803144200',
    projectId: 'multivendor-3f08e',
    storageBucket: 'multivendor-3f08e.appspot.com',
    iosClientId: '769803144200-3bokom7p0pdoop2t13osms24ajl8loj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendorAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEEuih9Hl7DpEwrtbwfng03q4Bo20F3fo',
    appId: '1:769803144200:ios:05f2eb9a9c600637df15bd',
    messagingSenderId: '769803144200',
    projectId: 'multivendor-3f08e',
    storageBucket: 'multivendor-3f08e.appspot.com',
    iosClientId: '769803144200-3bokom7p0pdoop2t13osms24ajl8loj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendorAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt1-qhKMb_Gvt1m8WBiU3H7zDet7HKBsU',
    appId: '1:769803144200:web:501a6dacf8a1b101df15bd',
    messagingSenderId: '769803144200',
    projectId: 'multivendor-3f08e',
    authDomain: 'multivendor-3f08e.firebaseapp.com',
    storageBucket: 'multivendor-3f08e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt1-qhKMb_Gvt1m8WBiU3H7zDet7HKBsU',
    appId: '1:769803144200:web:26ab85ac39bfb4c9df15bd',
    messagingSenderId: '769803144200',
    projectId: 'multivendor-3f08e',
    authDomain: 'multivendor-3f08e.firebaseapp.com',
    storageBucket: 'multivendor-3f08e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuquJcFSefLq7a4TeeACrtlTS0G-u1ZuM',
    appId: '1:769803144200:android:5ba427f739c6b241df15bd',
    messagingSenderId: '769803144200',
    projectId: 'multivendor-3f08e',
    storageBucket: 'multivendor-3f08e.appspot.com',
  );

}